name: Writing Dates
on:
  push:
    branches:
      - main
  schedule:
    - cron: '* * * * *'
jobs:
  write-dates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Write date
        run: |
          python src/script.py >> dates.txt
      - name: Commit changes
        run: |
          git config --local user.email "encinaesteban27@gmail.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Updating dates"
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
